
- name: Факел
  type: default
  ignored: true
  category: Light
  required:
    force_visible: true
    skills: { engineering: 1 }
    components:
      - class: WoodenDebris6
        count: 1
        check_type_of: false
      - class: [Bandage,Rag]
        count: 1
        check_type_of: false
        hp: 50%
  failed_handler:
    handler_type: "default" # порча предметов при недостаточном навыке.
    class: WoodenDebris2
    count: {min: 3, max: 6} # может быть диапазоном -> count: {min: 1, max: 4}
  result:
    class: TorchDisabled
    modifiers: null

- name: Деревянная ограда
  type: building
  ignored: true
  category: Building
  required:
    skills: { engineering: 13 }
    components:
      - class: WoodenDebris(1-5)
        count: 4
        check_type_of: false
  result:
    class: WoodenSmallFence

- type: interact
  ignored: true
  required:
    skills:
      farming: 2
    components:
      hand_item: 
        class: Knife
        hp:
          value: 50%
          message: "{basename.lower} повреждён"
      target:
        class: IFoodItem
        hp:
          value: 50%
          message: 
            - "{basename} слишком похерен"
            - "А хавчик то (попорчен|убит|наёбнут)"
  options:
    craft_duration: rta * 2
  failed_handler:
    handler_type: default
    class: OrganicDebris1
    count: 1
    
  result:
    sound: "damage/wood_(1-3).ogg" # (опционально) проигрыш звука при действии. (1-3) подставляет рандомное число
    # сообщение успешного действия
    emote: # (опционально) вызывает один из эмоутов. слова в круглых скобках являются рандомной заменой
      - "(рубит|кромсает) {target.lower} и получает {basename}."
      - "разделяет {target.lower} на мелкие кусочки и (производит|делает) {basename}."
      - "ловко оперирует {hand_item.lower} по {target.lower} возводя {basename}"
    class: Svetlolik
    modifiers:
      - name: default
        auto_all: true


- name: Пирог
  type: system
  ignored: true
  system_specific: FryingPanSystem
  required:
    force_visible: true
    skills:
      cooking: 1
    components:
      - class: Testo
        count: 2
  options:
    craft_duration: (rta * 2) + from_skill(30,2) + irnd(2,6)
  result:
    class: Pie
    modifiers:
      - name: set_name
        value: "Пирог с НАЧИНКОЙ"

- type: system
  ignored: true
  system_specific: BakingOvenSystem
  options:
    craft_duration: from_skill(5,2)
  required:
    force_visible: true
    skills:
      cooking: 1
    components:
      - class: Testo
        count: 2
      - class: IFoodItem
        name: Любая еда
        count: 1
        check_type_of: true
        meta_tag: OPTIONAL_FOOD
  result:
    class: Bread
    count: 1
    modifiers:
      - name: set_name
        value: "Пирог с {OPTIONAL_FOOD:name.lower}"

- type: system
  name: Лапшовое дело
  ignored: true
  desc: Тесто запихнуть в мясодавку
  system_specific: OrganicGrinderSystem
  required:
    components:
      - class: Testo
        count: 2
        meta_tag: TESTO_TAG
  result:
    class: Lapsha
    count: 1
    modifiers:
      - name: set_name
        value: "Лапша из {TESTO_TAG:name.lower}"