name: Sync changelogs on deploy release

on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog'
        required: true

jobs:
  UpdateChangelogs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Replace Changelog File
      run: |
        echo "$INPUT_CHANGELOG" > Src/CHANGELOGS.txt
      env:
        INPUT_CHANGELOG: ${{ github.event.inputs.changelog }}
    
    - name: Push changes
      uses: test-room-7/action-update-file@v1  
      if: github.repository == 'Relicta-Team/ReSDK_A3.vr'
      with:
        committer-name: Autoupdater
        file-path: |
          Src/CHANGELOGS.txt
        commit-msg: Update changelogs on release
        github-token: ${{secrets.TOKEN}}